global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dispatch-api'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'geo-index-service'
    static_configs:
      - targets: ['host.docker.internal:50051']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'flink-jobmanager'
    static_configs:
      - targets: ['flink-jobmanager:8081']
    metrics_path: '/metrics'

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['host.docker.internal:9308']

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:8123']
    metrics_path: '/metrics'
